### ISSUE TITLE
does it work?

### ISSUE THREAD

**Issue by PavloPoliakov** [jbarabander/node-vegeta#6]
I've just installed fresh `vegeta` and `node-vegate`. Put example into the file and executed with node - nothing happens, it just exits.

vegeta version:
```
Version: cli/v12.1.0
Commit: c120b942b43950d4237e41f31152706fbc3d4c0d
Runtime: go1.11.2 darwin/amd64
Date: 2018-11-17T05:18:18Z+0000
```

node version:
```
v8.9.4
```

after I run - it just exists. Do you expect it to work?

**Comment by jbarabander** [comment]
Hey!  I do indeed expect it to work but I apologize if it does not.  This sorta just started as a personal project.  By example file I assume you mean the example I put in the repo?  I will try to reproduce your issue.

**Comment by PavloPoliakov** [comment]
@jbarabander thanks for the quick answer. I meant this piece of code: https://github.com/jbarabander/scouter#basic .

**Comment by jbarabander** [comment]
Sure thing!  @PavelPolyakov looking at that basic example, it requires a targets.txt file to work.  Do you have a targets file?

**Comment by PavloPoliakov** [comment]
I did not, but I do have it right now. The result is the same.
Here is the video: https://monosnap.com/file/YbvMvlyKhRXxjaxBnls2wI5Y4P6bt3 .

I'm not sure if it should throw the errors when something is not fine.

**Comment by jbarabander** [comment]
@PavelPolyakov error handling is something I will be tackling very soon especially in light of these issues.  I am attempting to reproduce locally.  I will get back to you shortly.

**Comment by jbarabander** [comment]
@PavelPolyakov after looking into it I believe I have found the issue.  The example also seems to expect a body.json file.  Try removing the `.body('body.json')` portion of the command and see if then your file runs as expected.

**Comment by jbarabander** [comment]
@PavelPolyakov I will make sure to add more documentation and error handling shortly so that these kind of issues are more clear.  Sorry for the confusion!

**Comment by PavloPoliakov** [comment]
yes, without `body.json` it seems to do something :) Thanks, will continue my journey tomorrow.
Thanks for the package!

**Comment by jbarabander** [comment]
You are very very welcome! :) Thanks for giving it a try!
