### ISSUE TITLE
1.0.4 & 1.0.5 don't appear to be published on NPM or have git tags/releases

### ISSUE THREAD

**Issue by 9point6** [jbarabander/node-vegeta#9]
Hey, I've started using `node-vegeta` today and found that the most recent version installed by NPM is 1.0.3 (which doesn't line up with the README on the repo anymore)

**Comment by jbarabander** [comment]
Hey!  Thank you so much for using this package!  I will publish the versions mentioned so that you can pull them down from NPM!

**Comment by jbarabander** [comment]
It should be up to date now so feel free to install from npm.
